#+TITLE: Contributing

/This is just a first draft, feel free to complete and/or modify it./

** Goals

Our goal is to help attract and keep new users by improving the Emacs out of the box
(OOB) experience. Generally speaking, this means improving the default behaviours
and aesthetic of Emacs to reduce the absolute need for "customizing" Emacs so that,
on first launch, it can be considered a good/semi-intuitive tool by modern standards.

As such, appropriate changes will be relatively
lightweight and based largely on ~setq~ / ~defvar~ settings and well-established
ELPA packages, while generally avoiding ~defun~. For further details and discussion,
see: https://github.com/josteink/emacs-oob-reboot/issues/26

** Pull Requests

One concern at a time per request. This makes it easier to discuss it in
the comments.

** Issues

Create an issue instead of a pull request when you either don't have any patch
to offer or the proposed change seems at least a little dubious.

** Coding Guidelines

- Read http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html.
- Yes it is 2017, yes we all have 30'' monitors, but please avoid very long
  lines in the code you push.
- No leading whitespaces.
- No trailing whitespaces.
- When the code doesn't speak for itself, comment it.
